# Generated by Django 6.0.5 on 2026-05-27 02:28

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='enter first name', max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='enter middle name', max_length=20, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text='enter surname', max_length=50, verbose_name='Last Name')),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('is_active', models.BooleanField(default=False)),
                ('joined_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
